import characterization_structure_theory_multivariate_probability_foundation_canonical_lane_mathlib.GateLemmas
import characterization_structure_theory_multivariate_probability_foundation_canonical_lane_mathlib.FinalTheorem
